-- Create quiz battle system for friend-to-friend learning competitions
-- Tables: quiz_battles, battle_rounds, battle_participants, battle_stats
-- Includes RLS policies, indexes, triggers, and notifications

-- ============================================================================
-- TABLE: quiz_battles
-- Main battle entity tracking challenges between friends
-- ============================================================================

CREATE TABLE IF NOT EXISTS quiz_battles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Participants
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  opponent_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Battle configuration
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),
  source_folder_id UUID REFERENCES user_folders(id) ON DELETE SET NULL,
  source_folder_name TEXT NOT NULL,
  rounds_count INTEGER NOT NULL DEFAULT 3 CHECK (rounds_count > 0 AND rounds_count <= 5),
  questions_per_round INTEGER NOT NULL DEFAULT 5 CHECK (questions_per_round > 0 AND questions_per_round <= 20),

  -- Results
  winner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,

  -- Constraints
  CONSTRAINT valid_participants CHECK (created_by != opponent_id),
  CONSTRAINT valid_completion CHECK (
    (status = 'completed' AND completed_at IS NOT NULL) OR
    (status != 'completed' AND completed_at IS NULL)
  ),
  CONSTRAINT valid_winner CHECK (
    winner_id IS NULL OR winner_id IN (created_by, opponent_id)
  )
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_quiz_battles_created_by ON quiz_battles(created_by, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_battles_opponent ON quiz_battles(opponent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_battles_status ON quiz_battles(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_battles_folder ON quiz_battles(source_folder_id);

-- Comments
COMMENT ON TABLE quiz_battles IS 'Friend-to-friend quiz battles for learning competition';
COMMENT ON COLUMN quiz_battles.status IS 'pending = awaiting acceptance, active = in progress, completed = finished, cancelled = rejected';
COMMENT ON COLUMN quiz_battles.source_folder_id IS 'Challenger''s folder containing the quiz content';
COMMENT ON COLUMN quiz_battles.winner_id IS 'NULL = draw, otherwise user who won';

-- ============================================================================
-- TABLE: battle_rounds
-- Individual rounds within a battle, contains questions
-- ============================================================================

CREATE TABLE IF NOT EXISTS battle_rounds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Parent battle
  battle_id UUID NOT NULL REFERENCES quiz_battles(id) ON DELETE CASCADE,

  -- Round info
  round_number INTEGER NOT NULL CHECK (round_number > 0),

  -- Questions for this round (generated by AI)
  -- Format: [{id, question, options: [string], correctAnswer: number, topic: string}]
  questions JSONB NOT NULL,

  -- Timestamps
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,

  -- Constraints
  CONSTRAINT unique_battle_round UNIQUE (battle_id, round_number),
  CONSTRAINT valid_questions CHECK (jsonb_array_length(questions) > 0)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_battle_rounds_battle ON battle_rounds(battle_id, round_number);
CREATE INDEX IF NOT EXISTS idx_battle_rounds_started ON battle_rounds(started_at DESC);

-- Comments
COMMENT ON TABLE battle_rounds IS 'Individual rounds containing AI-generated questions';
COMMENT ON COLUMN battle_rounds.questions IS 'JSONB array of question objects with answers and topics';

-- ============================================================================
-- TABLE: battle_participants
-- Tracks each participant's answers and scores per round
-- ============================================================================

CREATE TABLE IF NOT EXISTS battle_participants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- References
  battle_id UUID NOT NULL REFERENCES quiz_battles(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  round_number INTEGER NOT NULL CHECK (round_number > 0),

  -- User's answers for this round
  -- Format: {question_id: selected_answer_index}
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Performance metrics
  score INTEGER NOT NULL DEFAULT 0 CHECK (score >= 0),
  time_taken INTEGER NOT NULL CHECK (time_taken >= 0), -- seconds

  -- Timestamp
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraints
  CONSTRAINT unique_participant_round UNIQUE (battle_id, user_id, round_number)
  -- Note: Participant validation is handled by RLS policies and API layer
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_battle_participants_battle_user ON battle_participants(battle_id, user_id);
CREATE INDEX IF NOT EXISTS idx_battle_participants_user ON battle_participants(user_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_battle_participants_round ON battle_participants(battle_id, round_number);

-- Comments
COMMENT ON TABLE battle_participants IS 'User answers and scores for each round';
COMMENT ON COLUMN battle_participants.answers IS 'JSONB object mapping question_id to selected answer index';
COMMENT ON COLUMN battle_participants.time_taken IS 'Time taken to complete round in seconds';

-- ============================================================================
-- TABLE: battle_stats
-- Aggregated statistics per user for tracking progress and weak/strong topics
-- ============================================================================

CREATE TABLE IF NOT EXISTS battle_stats (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Overall stats
  total_battles INTEGER NOT NULL DEFAULT 0 CHECK (total_battles >= 0),
  wins INTEGER NOT NULL DEFAULT 0 CHECK (wins >= 0),
  losses INTEGER NOT NULL DEFAULT 0 CHECK (losses >= 0),
  draws INTEGER NOT NULL DEFAULT 0 CHECK (draws >= 0),

  -- Topic analysis (learning insights)
  -- Format: {topic_name: count}
  weak_topics JSONB NOT NULL DEFAULT '{}'::jsonb,
  strong_topics JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Timestamps
  last_battle_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraints
  CONSTRAINT valid_battle_counts CHECK (total_battles = wins + losses + draws)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_battle_stats_total ON battle_stats(total_battles DESC);
CREATE INDEX IF NOT EXISTS idx_battle_stats_wins ON battle_stats(wins DESC);
CREATE INDEX IF NOT EXISTS idx_battle_stats_last_battle ON battle_stats(last_battle_at DESC);

-- Comments
COMMENT ON TABLE battle_stats IS 'Aggregated battle statistics and learning insights per user';
COMMENT ON COLUMN battle_stats.weak_topics IS 'JSONB object: {topic: wrong_answer_count} for learning recommendations';
COMMENT ON COLUMN battle_stats.strong_topics IS 'JSONB object: {topic: correct_answer_count} for confidence tracking';

-- ============================================================================
-- RLS POLICIES
-- Security rules ensuring users can only access their own battles
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE quiz_battles ENABLE ROW LEVEL SECURITY;
ALTER TABLE battle_rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE battle_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE battle_stats ENABLE ROW LEVEL SECURITY;

-- ===== quiz_battles policies =====

DROP POLICY IF EXISTS "Users can view their battles" ON quiz_battles;
CREATE POLICY "Users can view their battles"
  ON quiz_battles
  FOR SELECT
  USING (
    auth.uid() = created_by
    OR auth.uid() = opponent_id
  );

DROP POLICY IF EXISTS "Users can create battles" ON quiz_battles;
CREATE POLICY "Users can create battles"
  ON quiz_battles
  FOR INSERT
  WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can update their battles" ON quiz_battles;
CREATE POLICY "Users can update their battles"
  ON quiz_battles
  FOR UPDATE
  USING (
    auth.uid() = created_by
    OR auth.uid() = opponent_id
  )
  WITH CHECK (
    auth.uid() = created_by
    OR auth.uid() = opponent_id
  );

DROP POLICY IF EXISTS "Users can delete pending battles" ON quiz_battles;
CREATE POLICY "Users can delete pending battles"
  ON quiz_battles
  FOR DELETE
  USING (
    auth.uid() = created_by
    AND status = 'pending'
  );

-- ===== battle_rounds policies =====

DROP POLICY IF EXISTS "Users can view rounds from their battles" ON battle_rounds;
CREATE POLICY "Users can view rounds from their battles"
  ON battle_rounds
  FOR SELECT
  USING (
    battle_id IN (
      SELECT id FROM quiz_battles
      WHERE created_by = auth.uid() OR opponent_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "System can create rounds" ON battle_rounds;
CREATE POLICY "System can create rounds"
  ON battle_rounds
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "System can update rounds" ON battle_rounds;
CREATE POLICY "System can update rounds"
  ON battle_rounds
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- ===== battle_participants policies =====

DROP POLICY IF EXISTS "Users can view participants from their battles" ON battle_participants;
CREATE POLICY "Users can view participants from their battles"
  ON battle_participants
  FOR SELECT
  USING (
    battle_id IN (
      SELECT id FROM quiz_battles
      WHERE created_by = auth.uid() OR opponent_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can submit their own answers" ON battle_participants;
CREATE POLICY "Users can submit their own answers"
  ON battle_participants
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own answers" ON battle_participants;
CREATE POLICY "Users can update their own answers"
  ON battle_participants
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ===== battle_stats policies =====

DROP POLICY IF EXISTS "Users can view their own stats" ON battle_stats;
CREATE POLICY "Users can view their own stats"
  ON battle_stats
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "System can manage stats" ON battle_stats;
CREATE POLICY "System can manage stats"
  ON battle_stats
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- TRIGGER FUNCTIONS
-- Automated notifications and statistics updates
-- ============================================================================

-- ===== Trigger 1: Notify battle challenge =====
-- Sends notification when a user is challenged to a battle

CREATE OR REPLACE FUNCTION notify_battle_challenge()
RETURNS TRIGGER AS $$
DECLARE
  challenger_name TEXT;
BEGIN
  -- Only notify when battle is first created with pending status
  IF NEW.status = 'pending' THEN
    -- Get challenger's name
    SELECT COALESCE(
      raw_user_meta_data->>'full_name',
      raw_user_meta_data->>'name',
      email
    ) INTO challenger_name
    FROM auth.users
    WHERE id = NEW.created_by;

    -- Create notification for opponent
    PERFORM create_notification(
      NEW.opponent_id,
      'battle_challenge',
      'Quiz Battle Challenge!',
      challenger_name || ' challenged you to a quiz battle on "' || NEW.source_folder_name || '"',
      NEW.id,
      NEW.created_by,
      '/dashboard/social/battles/' || NEW.id,
      jsonb_build_object(
        'battle_id', NEW.id,
        'folder_name', NEW.source_folder_name,
        'rounds', NEW.rounds_count,
        'questions_per_round', NEW.questions_per_round
      )
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS notify_battle_challenge_trigger ON quiz_battles;

CREATE TRIGGER notify_battle_challenge_trigger
  AFTER INSERT ON quiz_battles
  FOR EACH ROW
  EXECUTE FUNCTION notify_battle_challenge();

-- ===== Trigger 2: Notify battle result =====
-- Sends notification when battle is completed with results

CREATE OR REPLACE FUNCTION notify_battle_result()
RETURNS TRIGGER AS $$
DECLARE
  challenger_name TEXT;
  opponent_name TEXT;
  winner_name TEXT;
  result_message TEXT;
BEGIN
  -- Only notify when status changes to completed
  IF OLD.status != 'completed' AND NEW.status = 'completed' THEN
    -- Get participant names
    SELECT COALESCE(
      raw_user_meta_data->>'full_name',
      raw_user_meta_data->>'name',
      email
    ) INTO challenger_name
    FROM auth.users
    WHERE id = NEW.created_by;

    SELECT COALESCE(
      raw_user_meta_data->>'full_name',
      raw_user_meta_data->>'name',
      email
    ) INTO opponent_name
    FROM auth.users
    WHERE id = NEW.opponent_id;

    -- Determine result message
    IF NEW.winner_id IS NULL THEN
      result_message := 'It''s a draw! Great effort from both of you.';
    ELSIF NEW.winner_id = NEW.created_by THEN
      winner_name := challenger_name;
      result_message := winner_name || ' won the battle!';
    ELSE
      winner_name := opponent_name;
      result_message := winner_name || ' won the battle!';
    END IF;

    -- Notify challenger
    PERFORM create_notification(
      NEW.created_by,
      'battle_result',
      'Battle Completed!',
      result_message,
      NEW.id,
      NEW.opponent_id,
      '/dashboard/social/battles/' || NEW.id || '/results',
      jsonb_build_object(
        'battle_id', NEW.id,
        'winner_id', NEW.winner_id,
        'is_draw', NEW.winner_id IS NULL,
        'is_winner', NEW.winner_id = NEW.created_by
      )
    );

    -- Notify opponent
    PERFORM create_notification(
      NEW.opponent_id,
      'battle_result',
      'Battle Completed!',
      result_message,
      NEW.id,
      NEW.created_by,
      '/dashboard/social/battles/' || NEW.id || '/results',
      jsonb_build_object(
        'battle_id', NEW.id,
        'winner_id', NEW.winner_id,
        'is_draw', NEW.winner_id IS NULL,
        'is_winner', NEW.winner_id = NEW.opponent_id
      )
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS notify_battle_result_trigger ON quiz_battles;

CREATE TRIGGER notify_battle_result_trigger
  AFTER UPDATE ON quiz_battles
  FOR EACH ROW
  EXECUTE FUNCTION notify_battle_result();

-- ===== Trigger 3: Update battle stats =====
-- Updates aggregated statistics when battle completes

CREATE OR REPLACE FUNCTION update_battle_stats()
RETURNS TRIGGER AS $$
DECLARE
  challenger_score INTEGER;
  opponent_score INTEGER;
  participant_record RECORD;
  round_record RECORD;
  question JSONB;
  user_answer INTEGER;
  correct_answer INTEGER;
  topic TEXT;
BEGIN
  -- Only update stats when status changes to completed
  IF OLD.status != 'completed' AND NEW.status = 'completed' THEN

    -- Calculate total scores for both participants
    SELECT COALESCE(SUM(score), 0) INTO challenger_score
    FROM battle_participants
    WHERE battle_id = NEW.id AND user_id = NEW.created_by;

    SELECT COALESCE(SUM(score), 0) INTO opponent_score
    FROM battle_participants
    WHERE battle_id = NEW.id AND user_id = NEW.opponent_id;

    -- Update stats for challenger
    INSERT INTO battle_stats (user_id, total_battles, wins, losses, draws, last_battle_at)
    VALUES (
      NEW.created_by,
      1,
      CASE WHEN NEW.winner_id = NEW.created_by THEN 1 ELSE 0 END,
      CASE WHEN NEW.winner_id = NEW.opponent_id THEN 1 ELSE 0 END,
      CASE WHEN NEW.winner_id IS NULL THEN 1 ELSE 0 END,
      NEW.completed_at
    )
    ON CONFLICT (user_id) DO UPDATE SET
      total_battles = battle_stats.total_battles + 1,
      wins = battle_stats.wins + CASE WHEN NEW.winner_id = NEW.created_by THEN 1 ELSE 0 END,
      losses = battle_stats.losses + CASE WHEN NEW.winner_id = NEW.opponent_id THEN 1 ELSE 0 END,
      draws = battle_stats.draws + CASE WHEN NEW.winner_id IS NULL THEN 1 ELSE 0 END,
      last_battle_at = NEW.completed_at,
      updated_at = NOW();

    -- Update stats for opponent
    INSERT INTO battle_stats (user_id, total_battles, wins, losses, draws, last_battle_at)
    VALUES (
      NEW.opponent_id,
      1,
      CASE WHEN NEW.winner_id = NEW.opponent_id THEN 1 ELSE 0 END,
      CASE WHEN NEW.winner_id = NEW.created_by THEN 1 ELSE 0 END,
      CASE WHEN NEW.winner_id IS NULL THEN 1 ELSE 0 END,
      NEW.completed_at
    )
    ON CONFLICT (user_id) DO UPDATE SET
      total_battles = battle_stats.total_battles + 1,
      wins = battle_stats.wins + CASE WHEN NEW.winner_id = NEW.opponent_id THEN 1 ELSE 0 END,
      losses = battle_stats.losses + CASE WHEN NEW.winner_id = NEW.created_by THEN 1 ELSE 0 END,
      draws = battle_stats.draws + CASE WHEN NEW.winner_id IS NULL THEN 1 ELSE 0 END,
      last_battle_at = NEW.completed_at,
      updated_at = NOW();

    -- Analyze topics for both participants
    FOR participant_record IN
      SELECT user_id, battle_id, round_number, answers
      FROM battle_participants
      WHERE battle_id = NEW.id
    LOOP
      -- Get questions for this round
      FOR round_record IN
        SELECT questions
        FROM battle_rounds
        WHERE battle_id = participant_record.battle_id
          AND round_number = participant_record.round_number
      LOOP
        -- Analyze each question
        FOR question IN SELECT * FROM jsonb_array_elements(round_record.questions)
        LOOP
          -- Extract user's answer and correct answer
          user_answer := (participant_record.answers->(question->>'id'))::INTEGER;
          correct_answer := (question->>'correctAnswer')::INTEGER;
          topic := question->>'topic';

          -- Skip if no topic
          CONTINUE WHEN topic IS NULL OR topic = '';

          -- Update weak/strong topics
          IF user_answer = correct_answer THEN
            -- Increment strong topic count
            UPDATE battle_stats
            SET strong_topics = jsonb_set(
              strong_topics,
              ARRAY[topic],
              to_jsonb(COALESCE((strong_topics->>topic)::INTEGER, 0) + 1)
            ),
            updated_at = NOW()
            WHERE user_id = participant_record.user_id;
          ELSE
            -- Increment weak topic count
            UPDATE battle_stats
            SET weak_topics = jsonb_set(
              weak_topics,
              ARRAY[topic],
              to_jsonb(COALESCE((weak_topics->>topic)::INTEGER, 0) + 1)
            ),
            updated_at = NOW()
            WHERE user_id = participant_record.user_id;
          END IF;
        END LOOP;
      END LOOP;
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS update_battle_stats_trigger ON quiz_battles;

CREATE TRIGGER update_battle_stats_trigger
  AFTER UPDATE ON quiz_battles
  FOR EACH ROW
  EXECUTE FUNCTION update_battle_stats();

-- ============================================================================
-- UPDATE NOTIFICATIONS TYPE CONSTRAINT
-- Add new battle notification types
-- ============================================================================

DO $$
BEGIN
  -- Drop old constraint if exists
  ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;

  -- Add new constraint with battle types
  ALTER TABLE notifications ADD CONSTRAINT notifications_type_check
    CHECK (type IN (
      'friend_request',
      'friend_accepted',
      'share',
      'achievement',
      'system',
      'course_join',
      'battle_challenge',
      'battle_result'
    ));
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- FINAL COMMENTS
-- ============================================================================

COMMENT ON TRIGGER notify_battle_challenge_trigger ON quiz_battles IS 'Sends notification to opponent when challenged';
COMMENT ON TRIGGER notify_battle_result_trigger ON quiz_battles IS 'Sends result notifications to both participants when battle completes';
COMMENT ON TRIGGER update_battle_stats_trigger ON quiz_battles IS 'Updates aggregated stats and topic analysis when battle completes';
