/**
 * Multi-Stage Async Content Processing Pipeline
 * 
 * Handles the complete flow from audio upload to final study materials
 * Supports both synchronous (polling) and asynchronous (webhook) modes
 * 
 * Pipeline Stages:
 * 1. uploading -> transcribing (RunPod)
 * 2. transcribing -> generating (OpenAI) 
 * 3. generating -> finalizing (PDF + Database)
 * 4. finalizing -> completed
 */

import { createClient } from '@/lib/supabase/server';
import { generateMindsyNotes, type MindsyNotesInput } from '@/lib/openai-client';

// Job status progression
export type JobStatus = 
  | 'uploading'      // Initial upload processing
  | 'transcribing'   // Audio being transcribed by RunPod
  | 'generating'     // Content being generated by OpenAI
  | 'finalizing'     // PDF generation and database saves
  | 'completed'      // All processing complete
  | 'failed';        // Processing failed at any stage

export interface ProcessingContext {
  jobId: string;
  userId: string;
  lectureTitle: string;
  courseSubject?: string;
  mode: 'sync' | 'async'; // sync = polling, async = webhooks
}

export interface TranscriptionData {
  text: string;
  detectedLanguage: string;
  languageConfidence?: number;
}

export interface GenerationData {
  masterContent: any;
  metadata: {
    title: string;
    language: string;
    estimatedStudyTime: string;
    difficulty: string;
  };
}

/**
 * Stage 1: Handle transcription completion from RunPod
 * Advances job from 'transcribing' -> 'generating' 
 */
export async function handleTranscriptionCompletion(
  jobId: string, 
  transcriptionData: TranscriptionData
): Promise<void> {
  console.log('🔄 Stage 1: Processing transcription completion for job:', jobId);

  try {
    // Use service role client for admin access (called from webhook context)
    const { createClient: createSupabaseAdmin } = await import('@supabase/supabase-js');
    const supabase = createSupabaseAdmin(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );
    
    // Get job details
    const { data: job, error: jobError } = await supabase
      .from('jobs')
      .select('*')
      .eq('job_id', jobId)
      .single();

    if (jobError || !job) {
      throw new Error(`Job not found: ${jobError?.message || 'Unknown error'}`);
    }

    // Save transcription to storage

    const txtPath = `${jobId}.txt`;
    await supabase.storage
      .from('generated-notes')
      .upload(txtPath, transcriptionData.text, {
        contentType: 'text/plain',
        cacheControl: '3600'
      });

    // Update job status to generating
    await supabase
      .from('jobs')
      .update({
        txt_file_path: txtPath,
        detected_language: transcriptionData.detectedLanguage,
        language_confidence: transcriptionData.languageConfidence,
        transcription_completed_at: new Date().toISOString(),
        status: 'generating' as JobStatus,
        updated_at: new Date().toISOString()
      })
      .eq('job_id', jobId);

    console.log('✅ Stage 1: Transcription saved, status updated to generating');

    // Continue to OpenAI generation (always sync for now, even in webhook mode)
    // TODO: Implement true OpenAI webhook when available
    await handleGenerationStage(jobId, transcriptionData, {
      jobId,
      userId: job.user_id,
      lectureTitle: job.lecture_title,
      courseSubject: job.course_subject,
      mode: 'sync' // Force sync for OpenAI until webhook is implemented
    });

  } catch (error) {
    console.error('❌ Stage 1 error:', error);
    await updateJobStatus(jobId, 'failed', error instanceof Error ? error.message : 'Transcription processing failed');
    throw error;
  }
}

/**
 * Stage 2: Handle OpenAI generation (sync or async)
 * Advances job from 'generating' -> 'finalizing'
 */
export async function handleGenerationStage(
  jobId: string,
  transcriptionData: TranscriptionData,
  context: ProcessingContext
): Promise<void> {
  console.log('🔄 Stage 2: Starting OpenAI generation for job:', jobId);

  try {
    // Prepare OpenAI input
    const mindsyNotesInput: MindsyNotesInput = {
      transcript: transcriptionData.text,
      lectureTitle: context.lectureTitle,
      courseSubject: context.courseSubject,
      detectedLanguage: transcriptionData.detectedLanguage
    };

    let generationResult;

    // Always use synchronous OpenAI generation (webhook support for OpenAI planned for future)
    console.log('🤖 Stage 2: Starting synchronous OpenAI generation...');
    generationResult = await generateMindsyNotes(mindsyNotesInput);
    
    if (!generationResult.success || !generationResult.masterContent) {
      throw new Error(`OpenAI generation failed: ${generationResult.error}`);
    }

    // Continue immediately to finalization
    await handleFinalizationStage(jobId, {
      masterContent: generationResult.masterContent,
      metadata: generationResult.masterContent.metadata || {}
    }, context);

  } catch (error) {
    console.error('❌ Stage 2 error:', error);
    await updateJobStatus(jobId, 'failed', error instanceof Error ? error.message : 'OpenAI generation failed');
    throw error;
  }
}

/**
 * Stage 3: Handle finalization (PDF generation, database saves)
 * Advances job from 'finalizing' -> 'completed'
 */
export async function handleFinalizationStage(
  jobId: string,
  generationData: GenerationData,
  context: ProcessingContext
): Promise<{ success: boolean; files: any; studyGuide: any }> {
  console.log('🔄 Stage 3: Starting finalization for job:', jobId);

  try {
    // Use service role client for admin access (called from webhook/async context)
    const { createClient: createSupabaseAdmin } = await import('@supabase/supabase-js');
    const supabase = createSupabaseAdmin(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );
    
    // Update status to finalizing
    await updateJobStatus(jobId, 'finalizing');

    // Save JSON file
    const jsonPath = `${jobId}.json`;
    await supabase.storage
      .from('generated-notes')
      .upload(jsonPath, JSON.stringify(generationData.masterContent, null, 2), {
        contentType: 'application/json',
        cacheControl: '3600'
      });

    // Save study guide to database
    console.log('💾 Stage 3: Saving study guide to database...');
    
    // Check what we're about to save
    console.log('📊 Data to save:', {
      hasQuestions: !!generationData.masterContent.questions,
      questionsLength: generationData.masterContent.questions?.length || 0,
      hasExplanations: !!generationData.masterContent.explanations,
      explanationsLength: generationData.masterContent.explanations?.length || 0,
      hasSummary: !!generationData.masterContent.summary,
      summaryKeys: generationData.masterContent.summary ? Object.keys(generationData.masterContent.summary) : []
    });
    
    const studyGuideData = {
      job_id: jobId,
      user_id: context.userId,
      title: context.lectureTitle,
      subject: context.courseSubject || null,
      language: generationData.masterContent.metadata?.language || 'en',
      questions: generationData.masterContent.questions || [],
      explanations: generationData.masterContent.explanations || [],
      summary: generationData.masterContent.summary || {},
      table_of_contents: generationData.masterContent.tableOfContents?.items
        ?.map((item: { title: string; description: string }) => `${item.title}: ${item.description}`)
        ?.join('\n') || '',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    };

    const { data: studyGuideRecord, error: studyGuideError } = await supabase
      .from('study_guides')
      .insert(studyGuideData)
      .select()
      .single();

    if (studyGuideError) {
      throw new Error(`Failed to save study guide: ${studyGuideError.message}`);
    }

    // Generate PDF
    console.log('📄 Stage 3: Generating PDF...');
    const { generateBeautifulPDF } = await import('@/lib/pdf-generator');
    const pdfBuffer = await generateBeautifulPDF(generationData.masterContent);
    const pdfPath = `${jobId}.pdf`;
    
    await supabase.storage
      .from('generated-notes')
      .upload(pdfPath, pdfBuffer, {
        contentType: 'application/pdf',
        cacheControl: '3600'
      });

    // Final job completion
    await supabase
      .from('jobs')
      .update({
        json_file_path: jsonPath,
        pdf_file_path: pdfPath,
        status: 'completed' as JobStatus,
        processing_completed_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      })
      .eq('job_id', jobId);

    console.log('✅ Stage 3: Finalization completed successfully');
    console.log('🎉 PIPELINE COMPLETED: Lecture processed successfully!', {
      jobId,
      title: context.lectureTitle,
      files: { json: jsonPath, pdf: pdfPath },
      studyGuideId: studyGuideRecord.id
    });

    return {
      success: true,
      files: {
        json: jsonPath,
        pdf: pdfPath
      },
      studyGuide: studyGuideRecord
    };

  } catch (error) {
    console.error('❌ Stage 3 error:', error);
    await updateJobStatus(jobId, 'failed', error instanceof Error ? error.message : 'Finalization failed');
    throw error;
  }
}

/**
 * Trigger OpenAI generation (future webhook implementation)
 */
async function triggerOpenAIGeneration(
  jobId: string, 
  transcriptionData: TranscriptionData
): Promise<void> {
  // TODO: Implement OpenAI webhook trigger
  // For now, this would submit to OpenAI with a webhook URL
  // Similar to how RunPod webhook works
  
  console.log('🔮 Future: Would trigger OpenAI webhook generation for:', jobId);
  
  // Placeholder - in the future this would:
  // 1. Submit to OpenAI with webhook URL
  // 2. Return immediately
  // 3. Let /api/openai-webhook handle the response
}

/**
 * Utility: Update job status
 */
async function updateJobStatus(
  jobId: string, 
  status: JobStatus, 
  errorMessage?: string
): Promise<void> {
  const supabase = await createClient();
  
  const updateData: any = {
    status,
    updated_at: new Date().toISOString()
  };

  if (errorMessage) {
    updateData.error_message = errorMessage;
  }

  if (status === 'failed' || status === 'completed') {
    updateData.processing_completed_at = new Date().toISOString();
  }

  await supabase
    .from('jobs')
    .update(updateData)
    .eq('job_id', jobId);
}