/**
 * Multi-Stage Async Content Processing Pipeline
 *
 * Handles the complete flow from audio upload to final study materials
 * Supports both synchronous (polling) and asynchronous (webhook) modes
 *
 * Pipeline Stages:
 * 1. uploading -> transcribing (RunPod)
 * 2. transcribing -> generating (Grok AI)
 * 3. generating -> finalizing (JSON + Database)
 * 4. finalizing -> completed
 */

import { createClient } from '@/lib/supabase/server';
import { generateStudentDeskContent, type MindsyNotesInput } from '@/lib/grok-client';

// Job status progression
export type JobStatus =
  | 'uploading'      // Initial upload processing
  | 'transcribing'   // Audio being transcribed by RunPod
  | 'generating'     // Content being generated by Grok AI
  | 'finalizing'     // JSON generation and database saves
  | 'completed'      // All processing complete
  | 'failed';        // Processing failed at any stage

export interface ProcessingContext {
  jobId: string;
  userId: string;
  lectureTitle: string;
  courseSubject?: string;
  mode: 'sync' | 'async'; // sync = polling, async = webhooks
}

export interface TranscriptionData {
  text: string;
  segments?: Array<{
    id: number;
    start: number;
    end: number;
    text: string;
  }>;
  detectedLanguage: string;
  languageConfidence?: number;
}

export interface GenerationData {
  masterContent: any;
  metadata: {
    title: string;
    language: string;
    estimatedStudyTime: string;
    difficulty: string;
  };
}

/**
 * Stage 1: Handle transcription completion from RunPod
 * Advances job from 'transcribing' -> 'generating' 
 */
export async function handleTranscriptionCompletion(
  jobId: string,
  transcriptionData: TranscriptionData
): Promise<void> {
  console.log('🔄 Stage 1: Processing transcription completion for job:', jobId);

  try {
    // Use service role client for admin access (called from webhook context)
    const { createClient: createSupabaseAdmin } = await import('@supabase/supabase-js');
    const supabase = createSupabaseAdmin(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Check if study guide already exists (prevent duplicate processing from webhook retries)
    const { data: existingGuide } = await supabase
      .from('study_guides')
      .select('id')
      .eq('job_id', jobId)
      .single();

    if (existingGuide) {
      console.log('⏭️  Stage 1: Study guide already exists, skipping duplicate processing');
      return;
    }

    // Get job details
    const { data: job, error: jobError } = await supabase
      .from('jobs')
      .select('*')
      .eq('job_id', jobId)
      .single();

    if (jobError || !job) {
      throw new Error(`Job not found: ${jobError?.message || 'Unknown error'}`);
    }

    // Save transcription to storage

    const txtPath = `${jobId}.txt`;
    const { error: uploadError } = await supabase.storage
      .from('generated-notes')
      .upload(txtPath, transcriptionData.text, {
        contentType: 'text/plain',
        cacheControl: '3600'
      });

    if (uploadError) {
      console.error('❌ Failed to upload transcript:', uploadError);
      throw new Error(`Failed to upload transcript: ${uploadError.message}`);
    }

    console.log('✅ Transcript file uploaded:', txtPath);

    // Update job status to generating with timestamped segments
    const { error: updateError } = await supabase
      .from('jobs')
      .update({
        txt_file_path: txtPath,
        timestamped_transcript: transcriptionData.segments || null,  // Save segments with timestamps
        detected_language: transcriptionData.detectedLanguage,
        language_confidence: transcriptionData.languageConfidence,
        transcription_completed_at: new Date().toISOString(),
        status: 'generating' as JobStatus,
        updated_at: new Date().toISOString()
      })
      .eq('job_id', jobId);

    if (updateError) {
      console.error('❌ Failed to update job with txt_file_path:', updateError);
      throw new Error(`Failed to update job: ${updateError.message}`);
    }

    console.log('✅ Stage 1: Transcription saved, txt_file_path updated in database');

    // Continue to Grok AI generation (always sync for now, even in webhook mode)
    // TODO: Implement true Grok webhook when available
    await handleGenerationStage(jobId, transcriptionData, {
      jobId,
      userId: job.user_id,
      lectureTitle: job.lecture_title,
      courseSubject: job.course_subject,
      mode: 'sync' // Force sync for Grok AI until webhook is implemented
    });

  } catch (error) {
    console.error('❌ Stage 1 error:', error);
    await updateJobStatus(jobId, 'failed', error instanceof Error ? error.message : 'Transcription processing failed');
    throw error;
  }
}

/**
 * Stage 2: Handle Grok AI generation (sync or async)
 * Advances job from 'generating' -> 'finalizing'
 */
export async function handleGenerationStage(
  jobId: string,
  transcriptionData: TranscriptionData,
  context: ProcessingContext
): Promise<void> {
  console.log('🔄 Stage 2: Starting Grok AI generation for job:', jobId);

  try {
    // Prepare Grok AI input
    const mindsyNotesInput: MindsyNotesInput = {
      transcript: transcriptionData.text,
      lectureTitle: context.lectureTitle,
      courseSubject: context.courseSubject,
      detectedLanguage: transcriptionData.detectedLanguage
    };

    let generationResult;

    // Always use synchronous Grok AI generation (webhook support for Grok planned for future)
    console.log('🤖 Stage 2: Starting synchronous Grok AI generation with StudentDesk format...');
    generationResult = await generateStudentDeskContent(mindsyNotesInput);

    if (!generationResult.success || !generationResult.content) {
      throw new Error(`Grok AI generation failed: ${generationResult.error}`);
    }

    // Continue immediately to finalization
    await handleFinalizationStage(jobId, {
      masterContent: generationResult.content,
      metadata: generationResult.content.metadata || {}
    }, context);

  } catch (error) {
    console.error('❌ Stage 2 error:', error);
    await updateJobStatus(jobId, 'failed', error instanceof Error ? error.message : 'Grok AI generation failed');
    throw error;
  }
}

/**
 * Stage 3: Handle finalization (PDF generation, database saves)
 * Advances job from 'finalizing' -> 'completed'
 */
export async function handleFinalizationStage(
  jobId: string,
  generationData: GenerationData,
  context: ProcessingContext
): Promise<{ success: boolean; files: any; studyGuide: any }> {
  console.log('🔄 Stage 3: Starting finalization for job:', jobId);

  try {
    // Use service role client for admin access (called from webhook/async context)
    const { createClient: createSupabaseAdmin } = await import('@supabase/supabase-js');
    const supabase = createSupabaseAdmin(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );
    
    // Update status to finalizing
    await updateJobStatus(jobId, 'finalizing');

    // Save JSON file
    const jsonPath = `${jobId}.json`;
    await supabase.storage
      .from('generated-notes')
      .upload(jsonPath, JSON.stringify(generationData.masterContent, null, 2), {
        contentType: 'application/json',
        cacheControl: '3600'
      });

    // Save study guide to database
    console.log('💾 Stage 3: Saving study guide to database...');

    // Check what we're about to save
    console.log('📊 Data to save (StudentDesk format):', {
      hasExplanations: !!generationData.masterContent.explanations,
      explanationsLength: generationData.masterContent.explanations?.length || 0,
      hasSummary: !!generationData.masterContent.summary,
      summaryKeys: generationData.masterContent.summary ? Object.keys(generationData.masterContent.summary) : [],
      note: 'Questions will be generated on-demand via quiz API'
    });

    const studyGuideData = {
      job_id: jobId,
      user_id: context.userId,
      title: context.lectureTitle,
      subject: context.courseSubject || null,
      language: generationData.masterContent.metadata?.language || 'en',
      questions: [], // Empty - quizzes will be generated on-demand
      explanations: generationData.masterContent.explanations || [],
      summary: generationData.masterContent.summary || {},
      table_of_contents: generationData.masterContent.overview?.keyObjectives
        ?.join('\n') || '',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    };

    const { data: studyGuideRecord, error: studyGuideError } = await supabase
      .from('study_guides')
      .insert(studyGuideData)
      .select()
      .single();

    if (studyGuideError) {
      throw new Error(`Failed to save study guide: ${studyGuideError.message}`);
    }

    // Skip PDF generation - requires puppeteer which doesn't work on Vercel
    console.log('📄 Stage 3: Skipping PDF generation (not needed for StudentDesk)');
    const pdfPath = null;

    // Final job completion
    await supabase
      .from('jobs')
      .update({
        json_file_path: jsonPath,
        pdf_file_path: pdfPath,
        status: 'completed' as JobStatus,
        processing_completed_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      })
      .eq('job_id', jobId);

    console.log('✅ Stage 3: Finalization completed successfully');
    console.log('🎉 PIPELINE COMPLETED: Lecture processed successfully!', {
      jobId,
      title: context.lectureTitle,
      files: { json: jsonPath, pdf: pdfPath },
      studyGuideId: studyGuideRecord.id
    });

    return {
      success: true,
      files: {
        json: jsonPath,
        pdf: pdfPath
      },
      studyGuide: studyGuideRecord
    };

  } catch (error) {
    console.error('❌ Stage 3 error:', error);
    await updateJobStatus(jobId, 'failed', error instanceof Error ? error.message : 'Finalization failed');
    throw error;
  }
}

/**
 * Trigger Grok AI generation (future webhook implementation)
 */
async function triggerGrokGeneration(
  jobId: string,
  transcriptionData: TranscriptionData
): Promise<void> {
  // TODO: Implement Grok AI webhook trigger
  // For now, this would submit to Grok with a webhook URL
  // Similar to how RunPod webhook works

  console.log('🔮 Future: Would trigger Grok AI webhook generation for:', jobId);

  // Placeholder - in the future this would:
  // 1. Submit to Grok AI with webhook URL
  // 2. Return immediately
  // 3. Let /api/grok-webhook handle the response
}

/**
 * Handle Document Processing (PDF, DOCX, TXT, DOC)
 * Skips transcription, goes directly to AI generation
 */
export async function handleDocumentProcessing(
  jobId: string,
  documentPaths: string[],
  context: ProcessingContext
): Promise<void> {
  console.log('🔄 Document Processing: Starting for job:', jobId);

  try {
    // Use service role client for admin access
    const { createClient: createSupabaseAdmin } = await import('@supabase/supabase-js');
    const supabase = createSupabaseAdmin(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Update status to processing
    await updateJobStatus(jobId, 'transcribing'); // Reusing transcribing status for document extraction

    // Extract text from all documents
    const { DocumentExtractor } = await import('@/lib/content-extractors/document-extractor');

    console.log('📄 Extracting text from documents...');
    const { combinedText, metadata } = await DocumentExtractor.extractMultipleDocuments(
      documentPaths,
      supabase
    );

    console.log(`✅ Document extraction completed: ${combinedText.length} characters from ${metadata.length} documents`);

    // Save extracted text to storage (like transcript)
    const txtPath = `${jobId}.txt`;
    const { error: uploadError } = await supabase.storage
      .from('generated-notes')
      .upload(txtPath, combinedText, {
        contentType: 'text/plain',
        cacheControl: '3600'
      });

    if (uploadError) {
      console.error('❌ Failed to upload extracted text:', uploadError);
      throw new Error(`Failed to upload extracted text: ${uploadError.message}`);
    }

    console.log('✅ Extracted text file uploaded:', txtPath);

    // Detect language from extracted text
    const { detectLanguageFromText } = await import('@/lib/language-utils');
    const detectedLanguage = await detectLanguageFromText(combinedText);

    // Update job status with extracted text path
    const { error: updateError } = await supabase
      .from('jobs')
      .update({
        txt_file_path: txtPath,
        detected_language: detectedLanguage,
        transcription_completed_at: new Date().toISOString(),
        status: 'generating' as JobStatus,
        updated_at: new Date().toISOString()
      })
      .eq('job_id', jobId);

    if (updateError) {
      console.error('❌ Failed to update job with txt_file_path:', updateError);
      throw new Error(`Failed to update job: ${updateError.message}`);
    }

    console.log('✅ Document extraction saved, proceeding to AI generation');

    // Prepare transcription data for generation stage
    const transcriptionData: TranscriptionData = {
      text: combinedText,
      detectedLanguage: detectedLanguage
    };

    // Continue to AI generation stage (same as audio pipeline)
    await handleGenerationStage(jobId, transcriptionData, context);

  } catch (error) {
    console.error('❌ Document processing error:', error);
    await updateJobStatus(jobId, 'failed', error instanceof Error ? error.message : 'Document processing failed');
    throw error;
  }
}

/**
 * Utility: Update job status
 */
async function updateJobStatus(
  jobId: string,
  status: JobStatus,
  errorMessage?: string
): Promise<void> {
  const supabase = await createClient();

  const updateData: any = {
    status,
    updated_at: new Date().toISOString()
  };

  if (errorMessage) {
    updateData.error_message = errorMessage;
  }

  if (status === 'failed' || status === 'completed') {
    updateData.processing_completed_at = new Date().toISOString();
  }

  await supabase
    .from('jobs')
    .update(updateData)
    .eq('job_id', jobId);
}